### PR TITLE
Relaxes minimum Julia dependency from version 1.1 to  1

### PR DESCRIPTION
**Pull request by zygmuntszpak**
Also bump patch version in preparation for a new release.

### CODE REVIEW

**Comment by johnnychen94** [comment]
You need to change CI settings as well to make sure 1.0 passes the test.

**Comment by zygmuntszpak** [comment]
I recall now why I had set the minimum version to 1.1. I made use of `Base.@kwdef` which was only introduced in Julia 1.1.

**Comment by johnnychen94** [comment]
Can you wait me for a few days to check that? I think 1.0 compatibility can be brought back relatively easy; usages of`Base.@kwdef` can be removed if we rewrite our struct more verbose.

**Comment by zygmuntszpak** [comment]
The thing is, I don't want the structures written more verbose :P.

**Pull request closed without merging**
